name: Build VBA Compatible Libmbus DLL

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Install MinGW
      run: choco install mingw

    - name: Configure with CMake
      run: cmake -G "MinGW Makefiles" -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build DLL
      run: cmake --build build --target ALL_BUILD

    - name: Upload DLL as artifact
      uses: actions/upload-artifact@v3
      with:
        name: libmbus-vba-dll
        path: build/*.dll
