name: Build Libmbus DLL

on: # Robot ne zaman çalışsın?
  push:
    branches:
      - main # Ana dalda değişiklik olduğunda çalışsın.
  pull_request:
    branches:
      - main # Ana dal için yapılan pull request'lerde çalışsın.

jobs: # Bu işlemi tanımlıyoruz.
  build: # İşin adı.
    runs-on: windows-latest # Windows ortamında çalışsın.

    steps:
      - name: Kaynak Kodları İndir
        uses: actions/checkout@v2 # GitHub'daki kaynak kodları indirir.

      - name: MinGW Kur
        run: choco install mingw # MinGW derleyicisini kurar.

      - name: CMake Yapılandırması
        run: cmake -G "MinGW Makefiles" -B build -DCMAKE_BUILD_TYPE=Release # DLL için derleme ayarları.

      - name: DLL Oluştur
        run: cmake --build build --target ALL_BUILD # DLL dosyasını oluşturur.

      - name: DLL Yükle
        uses: actions/upload-artifact@v3 # Oluşturulan DLL'i GitHub'a yükler.
        with:
          name: libmbus-dll # Yüklenen dosyanın adı.
          path: build/*.dll # DLL dosyasının yolu.
